name: Build and Deploy
on: [push]
permissions:
  contents: write
defaults:
  run:
    shell: bash
jobs:
  duckdb-wasm-extension:
    name: Experimental build for duckdb-wasm extension
    runs-on: ubuntu-22.04
    env:
      extension-name: 'quack'
    steps:
    - uses: mymindstorm/setup-emsdk@v12

    - name: Setup
      shell: bash
      run: |
        git clone https://github.com/carlopi/duckdb-wasm
        cd duckdb-wasm
        git checkout WIP
        git submodule init
        git submodule update

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: './duckdb-wasm/submodules/duckdb/extension/${{ github.event.repository.name }}'

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }} 

    - name: Build WebAssembly
      shell: bash
      run: |
        cd duckdb-wasm
        cp README.md ../${{ env.extension-name }}.extension.wasm
        
    - uses: actions/upload-artifact@v3
      with:
        name: Extension
        path: |
          ${{ env.extension-name }}.extension.wasm

  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    needs:
      - duckdb-wasm-extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          mkdir build

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.extension-name }}.extension.wasm
          path: build/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
